### ISSUE TITLE
Is there a significant difference between pretty-compact and pretty?

### ISSUE THREAD

**Issue by mignon-p** [monostable/haskell-kicad-data#11]
Just wondering if [`pretty-compact`](https://hackage.haskell.org/package/pretty-compact) produces noticeably better output than [`pretty`](https://hackage.haskell.org/package/pretty), in the context of `kicad-data`?  If the difference isn't that big, I wonder if it might be preferable to switch to `pretty` instead, because:

* `pretty` is more widely used
* `pretty` has a more liberal license

Neither of these is a big issue for me, but they both seem like small arguments in favor of `pretty`.

**Comment by kasbah** [comment]
I read [this blog post](https://jyp.github.io/posts/towards-the-prettiest-printer.html) at the time and decided to use it. It does seem to have some nicer formatting for s-expressions when you limit the page width. I don't think it's a huge issue though as the footprints are mostly for machine reading (are we even setting a page width?) so if it _is_ a problem for people I am happy to switch it out.

**Comment by mignon-p** [comment]
OK, thanks.  The blog post sheds some light on the reasons.  It isn't a problem for me; I was just curious why a more-obscure library was being used.
